# Generated by Django 5.1.4 on 2024-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehigh_app', '0002_appointment_rename_updated_date_blog_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='car_model',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
